receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 128
    spike_limit_mib: 32
  batch:
    timeout: 200ms
    send_batch_size: 256
    send_batch_max_size: 512
exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
    timeout: 1s
    sending_queue:
      queue_size: 128
    retry_on_failure:
      initial_interval: 1s
      max_interval: 5s
      max_elapsed_time: 10s
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/jaeger]
